name: Publish changed packages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Semantic monorepo release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Semantic monorepo
        uses: pekala/semantic-monorepo@6e6e12bf7e809eca97ce5bf4c5b3a2945fca5655
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
