name: Publish changed packages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Semantic monorepo release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Semantic monorepo
        uses: pekala/semantic-monorepo@5bb115191d3760d371f06e7802e80e3023bee0a8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
