name: Publish changed packages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Semantic monorepo release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pekala/semantic-monorepo@v1-release
