name: Publish changed packages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Semantic monorepo release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Semantic monorepo
        uses: pekala/semantic-monorepo@f3050a3f49e1b0f90f3a27bc027370493d4fbd09
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
